### ISSUE TITLE
not able to run the example demo

### ISSUE THREAD

**Issue by madabhaviamit** [Dirvann/video-conference-stitcher#1]
Getting below error,
![image](https://user-images.githubusercontent.com/29198504/109030346-b8834400-76e9-11eb-808b-b539c07d66e8.png)

**Comment by Dirvann** [comment]
- does the file exist in the path?
- what command did you use exactly?
- did you clone repo or used npm package?

**Comment by madabhaviamit** [comment]
Hi Dirk,

does the file exist in the path? -- Yes the files exist in the path..

what command did you use exactly? -- 
npm install
tsc
npm run example

did you clone repo or used npm package? -- cloned the repo and using the demo example from repo.

what os is this running on? -- 20.04.1 LTS

**Comment by Dirvann** [comment]
did you install ffmpeg?

**Comment by madabhaviamit** [comment]
> did you install ffmpeg?

yes, now i did and it works.. Earlier not having ffmpeg. What are the extensions supported for audio file recording? i will close this for now
